# Generated by Django 2.2 on 2020-11-10 16:41

import customer.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_of_birth', models.DateField(validators=[customer.models.validate_date_of_birth])),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('account_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
